export const GET_INVOICES = "get-invoices"
export const GET_INVOICE = "get-invoice"
export const CREATE_INVOICE = "create-invoice"
export const UPDATE_INVOICE = "update-invoice"
export const DELETE_INVOICE = "delete-invoice"
