export const ANNOUNCEMENT_QUERY_KEYS = {
  ANNOUNCEMENTS: "organization-announcements",
  ANNOUNCEMENT: "organization-announcement",
  CREATE_ANNOUNCEMENT: "organization-create-announcement",
  UPDATE_ANNOUNCEMENT: "organization-update-announcement",
  PUBLISH_ANNOUNCEMENT: "organization-publish-announcement",
  DELETE_ANNOUNCEMENT: "organization-delete-announcement",
} as const;

export const GET_ANNOUNCEMENTS = ANNOUNCEMENT_QUERY_KEYS.ANNOUNCEMENTS;
export const GET_ANNOUNCEMENT = ANNOUNCEMENT_QUERY_KEYS.ANNOUNCEMENT;
export const CREATE_ANNOUNCEMENT = ANNOUNCEMENT_QUERY_KEYS.CREATE_ANNOUNCEMENT;
export const UPDATE_ANNOUNCEMENT = ANNOUNCEMENT_QUERY_KEYS.UPDATE_ANNOUNCEMENT;
export const PUBLISH_ANNOUNCEMENT = ANNOUNCEMENT_QUERY_KEYS.PUBLISH_ANNOUNCEMENT;
export const DELETE_ANNOUNCEMENT = ANNOUNCEMENT_QUERY_KEYS.DELETE_ANNOUNCEMENT;
