export const COMPANY_POLICY_QUERY_KEYS = {
  COMPANY_POLICIES: "organization-company-policies",
  COMPANY_POLICY: "organization-company-policy",
  CREATE_COMPANY_POLICY: "organization-create-company-policy",
  UPDATE_COMPANY_POLICY: "organization-update-company-policy",
  DELETE_COMPANY_POLICY: "organization-delete-company-policy",
} as const;

export const GET_COMPANY_POLICIES = COMPANY_POLICY_QUERY_KEYS.COMPANY_POLICIES;
export const GET_COMPANY_POLICY = COMPANY_POLICY_QUERY_KEYS.COMPANY_POLICY;
export const CREATE_COMPANY_POLICY = COMPANY_POLICY_QUERY_KEYS.CREATE_COMPANY_POLICY;
export const UPDATE_COMPANY_POLICY = COMPANY_POLICY_QUERY_KEYS.UPDATE_COMPANY_POLICY;
export const DELETE_COMPANY_POLICY = COMPANY_POLICY_QUERY_KEYS.DELETE_COMPANY_POLICY;
