export const GET_FINANCE_ACCOUNTS = "GET_FINANCE_ACCOUNTS"
export const CREATE_FINANCE_ACCOUNT = "CREATE_FINANCE_ACCOUNT"
export const UPDATE_FINANCE_ACCOUNT = "UPDATE_FINANCE_ACCOUNT"
export const DELETE_FINANCE_ACCOUNT = "DELETE_FINANCE_ACCOUNT"
