export const KNOWLEDGE_BASE_ARTICLES = "KNOWLEDGE_BASE_ARTICLES"
export const CREATE_KNOWLEDGE_BASE_ARTICLE = "CREATE_KNOWLEDGE_BASE_ARTICLE"
export const UPDATE_KNOWLEDGE_BASE_ARTICLE = "UPDATE_KNOWLEDGE_BASE_ARTICLE"
export const DELETE_KNOWLEDGE_BASE_ARTICLE = "DELETE_KNOWLEDGE_BASE_ARTICLE"
