export const PERMISSION_QUERY_KEYS = {
  PERMISSIONS: "permissions",
  PERMISSION: "permission",
  CREATE_PERMISSION: "create-permission",
  UPDATE_PERMISSION: "update-permission",
  DELETE_PERMISSION: "delete-permission",
} as const

export const GET_PERMISSIONS = PERMISSION_QUERY_KEYS.PERMISSIONS
export const GET_PERMISSION = PERMISSION_QUERY_KEYS.PERMISSION
export const CREATE_PERMISSION = PERMISSION_QUERY_KEYS.CREATE_PERMISSION
export const UPDATE_PERMISSION = PERMISSION_QUERY_KEYS.UPDATE_PERMISSION
export const DELETE_PERMISSION = PERMISSION_QUERY_KEYS.DELETE_PERMISSION
