export const SETTINGS_QUERY_KEYS = {
  SETTINGS: "admin-settings",
  SETTINGS_BY_CATEGORY: "admin-settings-by-category",
  ADVANCED_SETTINGS: "admin-settings-advanced",
  APPEARANCE_SETTINGS: "admin-settings-appearance",
  EMAIL_SETTINGS: "admin-settings-email",
  UPDATE_SETTINGS: "admin-settings-update",
  UPDATE_ADVANCED_SETTINGS: "admin-settings-update-advanced",
  UPDATE_APPEARANCE_SETTINGS: "admin-settings-update-appearance",
  UPDATE_EMAIL_SETTINGS: "admin-settings-update-email",
} as const;

export const GET_SETTINGS = SETTINGS_QUERY_KEYS.SETTINGS;
export const GET_SETTINGS_BY_CATEGORY = SETTINGS_QUERY_KEYS.SETTINGS_BY_CATEGORY;
export const GET_ADVANCED_SETTINGS = SETTINGS_QUERY_KEYS.ADVANCED_SETTINGS;
export const GET_APPEARANCE_SETTINGS = SETTINGS_QUERY_KEYS.APPEARANCE_SETTINGS;
export const GET_EMAIL_SETTINGS = SETTINGS_QUERY_KEYS.EMAIL_SETTINGS;
export const UPDATE_SETTINGS = SETTINGS_QUERY_KEYS.UPDATE_SETTINGS;
export const UPDATE_ADVANCED_SETTINGS = SETTINGS_QUERY_KEYS.UPDATE_ADVANCED_SETTINGS;
export const UPDATE_APPEARANCE_SETTINGS = SETTINGS_QUERY_KEYS.UPDATE_APPEARANCE_SETTINGS;
export const UPDATE_EMAIL_SETTINGS = SETTINGS_QUERY_KEYS.UPDATE_EMAIL_SETTINGS;
